
services:
    books-store:
        image: postgres:16
        container_name: books-store
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
            - /home/rigo/pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - mi-red
        restart: unless-stopped
    mi-redis:
        image: redis:latest
        container_name: mi-redis
        ports:
            - "6379:6379"
        networks:
            - mi-red
        restart: unless-stopped
networks:
    mi-red:
        external: true
